### ISSUE TITLE
Simple Bar - Big Sur

### ISSUE THREAD

**Issue by bonkaj** [Jean-Tinland/simple-bar#14] opened 2020-09-14 19:43 UTC
Hello, I am trying to use simple-bar on Big Sur, and I believe an error is occurring. The top left part of the bar displays the following: 
![image](https://user-images.githubusercontent.com/19841863/93130807-aca24900-f698-11ea-9562-d8616b2cd0e8.png)

**Comment by Jean-Tinland** [comment] 2020-09-15 07:25
Hi!
I haven't tested simple-bar on Big Sur yet since I haven't installed it and I don't know if I'ill be able to do it before the official release.
I'm planning to switch on Big Sur as soon as it is launched so I will fix this at this time.

I'll let this issue open in the mean time.

**Comment by bonkaj** [comment] 2020-09-16 01:30
Thank you for responding. Unfortunately, I do not have the skills to help. I appreciate you sharing this software!

**Comment by lukebrb** [comment] 2020-09-17 19:25
Also getting some weird "unexpected token const" errors regarding Pywal.js on Big Sur. Otherwise, this is great — thanks for sharing this!

**Comment by MikoMagni** [comment] 2020-11-16 06:02
@Jean-Tinland have you tested Yabai and SimpleBar on Big Sur?  Not in any rush to upgrade till i sort all of my brew packages.

**Comment by Jean-Tinland** [comment] 2020-11-16 13:53
There has been some issue at start but they were fixed directly in `yabai` ([details here](https://github.com/Jean-Tinland/simple-bar/issues/52)).

I upgraded to Big Sur and with `yabai` and `Übersicht` up to date everything is working as expected.

I just need to replicate the Pywal error and fix it if necessary before closing this issue. :)

**Comment by Jean-Tinland** [comment] 2020-11-17 14:57
@lukebrb I couldn't reproduce your problem.

Does your Pywal.js file looks like something like this?

```javascript
export const Pywal = {
  cursor: '#d1dbe0',
  number: '#d1dbe0',
  parens: '#BFC3B9',
  result: '#94A4A8',
  comment: '#92999c',
  matched: '#94A4A8',
  function: '#376089',
  operator: '#708C9F',
  variable: '#507495',
  scrollbar: '#708C9F',
  separator: '#708C9F',
  background: '#0a0e0d',
  editorbackground: '#0a0e0d'
}
```

**Comment by MikoMagni** [comment] 2020-11-22 05:58
@Jean-Tinland I finally did a fresh install of Big Sur, I'm also unable to reproduce the Pywal issue with simple-bar.

**Comment by Jean-Tinland** [comment] 2020-11-24 09:34
Thanks @MikoMagni for testing this, I'll close this issue. Feel free to open it again if necessary.

**Closed by Jean-Tinland** 2020-11-24 09:34 UTC
Labels: bug

**Comment by typkrft** [comment] 2021-02-23 20:51
This happened to me. The problem seems to be that the pywal-gen.sh script is adding -n to the beginning of my Pywal.js file. Changing  `echo -n` to just `echo` seems to have resolved it. I am not sure why it's literally adding -n and not just doing what the flag is supposed to do.
