### ISSUE TITLE
Freezes computer every so often

### ISSUE THREAD

**Issue by figurativly1984** [Jean-Tinland/simple-bar#348] opened 2023-05-28 18:35 UTC
I'm pretty sure that either simple-bar or Ubersicht is causing my computer to freeze every so often. Simple-bar just stops working, Ubersicht stops responding, and my keyboard stops working for some reason? Even force quitting Ubersicht doesn't help and the only solution I've found so far is to just completely restart my computer. Then it continues working for a while and then freezes the computer again. I don't know what triggers this as it seems to happen randomly but I've checked Activity Monitor and every time that this happens there is just a whole lot of processes called something like osascript. I'm on an M2 mac if that's relevant.

**Comment by adi-panda** [comment] 2023-06-02 14:10
Disregard above, I don't think this is the issue.

**Comment by sputtene** [comment] 2023-06-11 16:12
Do you set up simple-bar refresh commands (`osascript -e 'tell application id "tracesOf.Uebersicht" to refresh widget id "simple-bar-index-jsx"'`) in your .yabairc for various focus/window/space changed/created/... events?

If so, try commenting those out; simple-bar sets this up itself in `./lib/scripts/init.sh` and you'll end up with multiple "refresh widget" invocations when one of these events fires.

I found that out by checking `ps auxww` when my system started to feel sluggish, but before it became unresponsive. There were more than 170 invocations (and increasing over time) of the `refresh widget "simple-bar-index-jsx"`; it looked like the events got generated more rapidly than they could be processed and closed.

`yabai -m signal --list` also showed a huge list of duplicate signals to refresh simple-bar, so changing for example the active window, would fire the osascript command 10+ times.

After commenting out the signals commands in my .yabairc, I haven't had problems anymore.

**Comment by figurativly1984** [comment] 2023-06-11 19:14
Here's what comes up when I run ``yabai -m signal --list`` :
<img width="698" alt="Screenshot 2023-06-11 at 12 06 05 PM" src="https://github.com/Jean-Tinland/simple-bar/assets/127815982/dfb6fa12-077e-421d-b257-9772be5d5c4c">
My .yabairc is just the default example that I haven't really changed other than playing with some of the values that it came with by default. I've disabled all of the widgets in simple-bar other than the clock but my computer still becomes unresponsive at seemingly random times. When it does act up, simple-bar doesn't update (e.g. the clock is frozen at a previous time) and when I try to force quit Ubersicht it completely freezes my computer if it hadn't already. When I check activity monitor, there are a lot of 'osascript' and 'yabai' processes. I'm not the most computer savvy so really puzzled as to what might be causing this.

**Comment by sputtene** [comment] 2023-06-11 19:40
If those are the only signal actions that are registered in yabai, that looks good. I had multiple entries for the same event, which caused multiple invocations to the osascript to update simple-bar in my case.

You say that there are lots of osascript and yabai processes. That should not happen.

There should be one yabai process running (the one managing your windows). Multiple osascript processes look to me like what I had: yabai fires multiple osascript instances in rapid succession to update the simple-bar widget, but for some reason these hang (or are queued and take a long time to finish*), which slowly but surely exhausts the available CPU cycles and memory in your computer.

I have no idea what causes this or how to solve it in your case.

\* I have observed that these processes do finish from time to time: when I had 170+ osascript processes running and keeping an eye on the number of those processes when my machine was running slowly, I saw the number decrease very slowly (about 1 osascript process finished each minute or so).

My gut feeling tells me that the problem is with Übersicht: it doesn't handle the osascript calls quickly, so there is a backlog building up, which eventually exhausts all system resources.
I might be wrong though, I haven't studied how the osascript triggers are handled.

**Comment by Jean-Tinland** [comment] 2023-11-27 11:20
I'm closing this issue as it doesn't have recent activity and I don't have other reports of freezing computers due to simple-bar.

Feel free to open a new issue if the issue persists.

**Comment by WantToLearnJapanese** [comment] 2023-12-02 07:43
I also have a freezing issue.

**Comment by levifig** [comment] 2024-01-04 00:05
I've also had the freezing issue. It's not new. I stopped using yabai months ago because of this issue, and now that I tried it again, with updated versions of yabai, ubersicht, and simple-bar, the issue remains: `osascript` tasks go rampant, hangs Ubersicht, eventually freezing my screen completely (remote via SSH still works) and the only solution is to reboot the machine (killing all `osascript` processes doesn't bring UI back, nor does killing `yabai`, `Übersicht`, `loginwindow`, etc).

**Comment by Jean-Tinland** [comment] 2024-01-04 08:41
Okay so it seems to be related to an overload of yabai signals hanging on `osascript` processes pilling up until nothing works anymore.

I don't think I can directly solve this issue in simple-bar as executing these osascript commands are the only way to refresh it for now.

However I am working on a server that will provide an alternative to applescript allowing to refresh simple-bar with simple `curl` on the fly thus giving me full hand to optimize refreshes and prevent piling of refresh request. This is not ideal as it imply installing another thing but this is the best I can offer at the moment :)

You can follow my progress in the original issue #205 or in [simple-bar-server repo](https://github.com/Jean-Tinland/simple-bar-server).

**Comment by Jean-Tinland** [comment] 2024-03-01 16:17
`simple-bar-server` is out and should resolve this issue. You'll find its repo [here](https://github.com/Jean-Tinland/simple-bar-server).

**Closed by Jean-Tinland** 2024-03-01 16:17 UTC
Labels: bug
