### ISSUE TITLE
[Components] No Music/Apple Music container

### ISSUE THREAD

**Issue by christo-ph** [Jean-Tinland/simple-bar#58] opened 2020-11-27 18:11 UTC
While hearing music via Apple Music App, or Spotify web or Apple Music web, I cannot see any title in the bar.

It seems, that simple-bar also not recongize the Music App from Apple. 

<img width="3001" alt="image" src="https://user-images.githubusercontent.com/16965068/100475717-1d77cf80-30e4-11eb-82e4-509125998f11.png">

Am I doing something wrong here? I enabled all Widgets.

Thanks for the great work.

**Comment by Jean-Tinland** [comment] 2020-11-27 18:44
There is indeed a bug with the Music widget on Big Sur, I'll try to fix it as soon as possible.

The Browser Track widget is working only with Google Chrome, Microsoft Edge or Safari with an opened youtube video.

As for the Spotify widget it is working only with the desktop app.

Thanks for using simple-bar :)

**Comment by Jean-Tinland** [comment] 2020-11-28 20:56
If you pull the latest version of simple-bar the Spotify & Musics widgets should be working well with each of the desktop apps on Big Sur.

As for the BrowserTrack widget I need to take another look a it because I couldn't make it work for now.

**Comment by christo-ph** [comment] 2020-11-28 21:15
Hi, after pulling the latest changes I got:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/16965068/100526216-170e5400-31c7-11eb-976c-93b8f5a1843b.png">

in the whole widget area of simple-bar. CPU runs to 100% and degrees. Also after a restart.

**Comment by christo-ph** [comment] 2020-11-28 21:17
After checking out 256059167210dc8640424cef76773352ce3a3383 everything back to normal.

**Comment by Jean-Tinland** [comment] 2020-11-28 21:18
Weird, I'll look into it tomorrow

**Comment by Jean-Tinland** [comment] 2020-11-29 15:29
The only difference between these two commits is 1 line.

Before:
```shell
if contains $(sw_vers -productVersion) "10.15"; then
```

After:
```shell
if [ $(sw_vers -productVersion) = "10.15" ]; then
```

I don't know what could cause this error for now... (see 38cd1ce47f83d3b4135441058aaa0cf93753cd5e).

**Comment by christo-ph** [comment] 2020-11-29 16:28
Ok, will try to reproduce this again. I saw that too.

**Comment by christo-ph** [comment] 2020-11-29 20:50
Here a screen capture from the behaviour:

![Bildschirmaufnahme 2020-11-29 um 21 38 16](https://user-images.githubusercontent.com/16965068/100553097-0673e180-328c-11eb-8255-e236b3e80b94.gif)

The activity before checking out master:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/16965068/100553172-85691a00-328c-11eb-8ce7-ebc12cf41f4b.png">

And after checking out master:

<img width="453" alt="image" src="https://user-images.githubusercontent.com/16965068/100553202-bcd7c680-328c-11eb-8352-fa6a3c36f1a2.png">

It seems that something went wrong and some process tries to restart so often, that those processes, especially launcher service, run hot.

**Comment by christo-ph** [comment] 2020-11-29 21:16
Hi, I think the root cause is this:

https://github.com/matryer/bitbar-plugins/issues/112#issuecomment-179387608

When playing music from the Apple Music "Listen now", "Recommended" etc it is not possible to use 

```
MUSIC_TRACK_NAME=$(osascript -e 'tell application "'$MUSIC_PROCESS'" to name of current track as st
MUSIC_ARTIST_NAME=$(osascript -e 'tell application "'$MUSIC_PROCESS'" to artist of current track as
```

Its back from 2016 but seems to be still valid.... I get 

```
❯ osascript -e 'tell application "'Music'" to name of current track as string'
53:59: execution error: name of «class pTrk» of application "Music" kann nicht in Typ string umgewandelt werden. (-1700)
```

if I am playing music from "listen now"

And simple-bar stops working after that. If I am playing songs from my playlists afterwards, it works properly.

**Comment by christo-ph** [comment] 2020-11-29 22:12
Hm. Reading again two comments below (https://github.com/matryer/bitbar-plugins/issues/112#issuecomment-219566250), it was fixed in iTunes. Wonder why this now happens with Music App.

**Comment by Jean-Tinland** [comment] 2020-12-01 11:16
I just pushed a fix attempt. 
I simply trap the error code when the music widget command fail.

Let me know if this solves your issue, I can't reproduce the problem since I don't have a premium subscribtion to Apple Music.

**Comment by christo-ph** [comment] 2020-12-01 13:31
Hi, thanks. It was still struggling. I had a look at your code, and I think you piped the stderr to stdout, but the erroneous return code was still responsible for the crash I suppose.

I‘ve made a PR (https://github.com/Jean-Tinland/simple-bar/pull/64) , which has some minor changes. It also shows the widget if the error occurs with 'unknown artist/track'.

I think you also have to replace `2>&1` in `tr` and other calls with `2>/dev/null` on other places. Also in the lower to command, you only added this to `tr`, not to `osascript`.

**Comment by Jean-Tinland** [comment] 2020-12-04 14:59
I merged your pull request in master, let me know if everything is fine. Thanks for you contribution :)

**Closed** 2020-12-04 16:54 UTC
Labels: bug
